<?php

function contact_alter_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'contact_site_form') {
    // hides the 'send yourself a message' checkbox and sets its value to checked
    $form['copy']['#type'] = 'hidden';
    $form['copy']['#default_value'] = 1;
    // hides the 'subject' input and sets its value to 'Feedback'
    $form['subject']['#type']= 'hidden';
    $form['subject']['#default_value'] = "Feedback";

  }
}
